---
title: "NY NOAA DATA ANALYSE"
---

### NY NOAA DATASET
####Source:
Menne, Matthew J., Imke Durre, Bryant Korzeniewski, Shelley McNeal, Kristy Thomas, Xungang Yin, Steven Anthony, Ron Ray, Russell S. Vose, Byron E.Gleason, and Tamara G. Houston (2012): Global Historical Climatology Network - Daily (GHCN-Daily), Version 3. [indicate subset used]. NOAA National Climatic Data Center. doi:10.7289/V5D21VHZ [August 15, 2017].

####Description:
Global Historical Climate Network includes daily land surface observations from around the world. The GHCN-Daily was developed to meet the needs of climate analysis and monitoring studies that require data at a sub-monthly time resolution (e.g., assessments of the frequency of heavy rainfall, heat wave duration, etc.). The dataset includes observations from World Meteorological Organization, Cooperative, and CoCoRaHS networks. If observed, the station dataset includes max and minimum temperatures, total precipitation, snowfall, and depth of snow on ground. Some U.S. station data are typically delayed only 24 hours.

####Varaibles:
 id: Weather station ID
 
 date: Date of observation
 
 prcp: Precipitation (tenths of mm)
 
 snow: Snowfall (mm)
 
 snwd: Snow depth (mm)
 
 tmax: Maximum temperature (tenths of degrees C)
 
 tmin: Minimum temperature (tenths of degrees C)
